### PR TITLE
Add illustration to Design System homepage

### PR DESCRIPTION
**Pull request by CharlotteDowns**
Screenshot of Design System homepage with illustration

## Cross-browser testing

- [x] Internet Explorer 11 (OB)
- [x] Edge (CD)
- [x] Chrome (OB)
- [x] Firefox (CD)
- [x] Safari (OB)
- [x] Chrome (Android) (CD)
- [x] Safari (iOS) (OB)
- [x] Firefox w/ colours overridden (OB)
- [x] Edge w/ High Contrast Mode (CD)

### CODE REVIEW

**Comment by CharlotteDowns** [comment]
Need to work on how this looks on mobile.

**Comment by CharlotteDowns** [comment]
@36degrees is this on the right lines? If so I can make the spacing changes flagged by the tests. 

Weird one as to where to put the image in our current file structure.

**Comment by 36degrees** [comment]
Pushed some additional commits to simplify the CSS. Having played around with different viewport sizes, I'm 99% sure it provides the same experience but worth double checking.

Had a quick test in a few different browsers, but probably needs a more thorough check before we merge this.

SVG is 2.3 kB gzipped, which I think is a reasonable price to pay for its awesomeness ✨ .

**Review by 36degrees — APPROVED** [review]
🎨 &nbsp;👩🏻‍🎨&nbsp; 🚀

**Pull request merged**
