### PR TITLE
Typo fix: Lowercase m for Minimum

### PR DESCRIPTION
**Pull request by frankieroberto**
Spotted this minor inconsistency.

### CODE REVIEW

**Review by owenatgov — APPROVED** [review]
Easy peasy. Thanks Frankie! Will wait for a 2nd approval so that we're following due process.

**Comment by querkmachine** [comment]
Now I'm actually looking I can see a few places where we've upper-capped "Minimum", like [the colours page](https://design-system.service.gov.uk/styles/colour/#colour-contrast), [password pattern](https://design-system.service.gov.uk/patterns/passwords/#wcag-copy-paste-password) and [help users create accounts](https://design-system.service.gov.uk/patterns/create-accounts/#wcag-avoid-cognitive-test). 

Not to say this PR should blam them all, but probably worth a systematic look at the content now that this has been brought up.

**Comment by frankieroberto** [comment]
(just spotted this whilst watching the show-and-tell! 🙌 )

**Comment by 36degrees** [comment]
Just a thought – WCAG seems to treat the different success criterion as proper nouns and title cases them everywhere in their own guidance. Should we follow suit instead?

It may make it clearer that we're referring to a specific thing rather than e.g the general concept of 'redundant entry'

**Comment by 36degrees** [comment]
As an alternative option, I've raised another PR which consistently uses proper nouns for the success criteria – https://github.com/alphagov/govuk-design-system/pull/3555

**Comment by calvin-lau-sig7** [comment]
Thanks all! 

Currently I'd stuck with sentence case as we've done here. E.g.:
> Focus not obscured (minimum)

[Style guide on capitalisation](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#capitalisation) says to "Always use sentence case, even in page titles and service names", which I'd probably put these criteria down as.

**Review by calvin-lau-sig7 — APPROVED** [review]

**Comment by frankieroberto** [comment]
@calvin-lau-sig7 @owenatgov can you approve the workflow, and then I think this can be merged?

**Comment by querkmachine** [comment]
Closing as this was superseded by #3886.

**Pull request closed without merging**
