### PR TITLE
Remove screen reader use assumption

### PR DESCRIPTION
**Pull request by amyhupe**
Brilliant addition! Hope you don't mind a small suggestion from a big fan ;)

This PR tweaks the copy to acknowledge that not all screen reader users are blind or visually-impaired and so _may_ see the input prefix or suffix.

### CODE REVIEW

**Comment by StephenGill** [comment]
Hi @amyhupe 👋, good point.

How about - `Do not rely on prefixes or suffixes alone, because screen readers won't perceive them.`

That way it's about what the tech can perceive rather than the person?

**Comment by amyhupe** [comment]
Sounds good to me - perhaps "will not" to remove the negative contraction?

**Comment by 36degrees** [comment]
I'm not sure it's right to say that a screen reader "perceives" anything – if we're going to focus around the technology, would it make more sense to say something like "Do not rely on prefixes or suffixes alone, because they are hidden from screen readers"?

**Comment by StephenGill** [comment]
'Do not rely on prefixes or suffixes alone, because screen readers will not read them out' ?

**Comment by 36degrees** [comment]
@amyhupe just wanted to check if you're happy with Stephen's suggested changes? If so I'm happy to update the PR for you and we can look at getting this merged 🙂

**Comment by amyhupe** [comment]
Oops yes happy for this to be changed :)

**Review by 36degrees — APPROVED** [review]

**Review by vanitabarrett — APPROVED** [review]

**Pull request merged**
