### PR TITLE
Add google tag manager

### PR DESCRIPTION
**Pull request by joelanman**
This adds google tag manager code. It uses the same file naming as the Prototype Kit and Elements.

### CODE REVIEW

**Comment by 36degrees** [comment]
Do we need to ensure that GTM is only initialised when it's deployed to production? I.e. that it's not included when running locally?

**Comment by igloosi** [comment]
yeah, pk has a heroku config var and conditional. how do you setup a config bar on PAAS?

**Comment by 36degrees** [comment]
Probably need to look at using something like [metalsmith-env](https://www.npmjs.com/package/metalsmith-env) and setting environment variables when travis builds to deploy. @alex-ju does that sound sane or is there a better way?

**Comment by joelanman** [comment]
I'm not sure we need to worry - GA only works on domains you tell it to. Otherwise anyone can add your public GA code and mess with your stats.

**Comment by joelanman** [comment]
prototype kit has vars because it's primarily designed for people to run their own instances, and it would be bad practice for us to be able to see all their stats if we chose to (we control the GA account)

**Comment by alex-ju** [comment]
@36degrees yes, metalsmith-env is a good way to set envs, played with a few weeks ago.

**Comment by 36degrees** [comment]
If we can address Alex's comments about paths then I think this can be merged.

**Comment by alex-ju** [comment]
Would be nice, but not a must since there's already a mix of short and relative paths.

**Comment by joelanman** [comment]
yeh I copied code that already used that syntax in design system - we can do another PR if we want to change that across the board

**Pull request merged**
