### PR TITLE
Stop deploying the Design System to PaaS

### LINKED ISSUE #3342: Remove existing Deploy GitHub workflow

### PR DESCRIPTION
**Pull request by 36degrees**
We’ve migrated the Design System from PaaS (which [is being decommissioned][1]) to Netlify.

We no longer need to deploy the Design System to PaaS, so we can remove the deploy workflow (as well as the ability to upload the built site as an artefact from the test workflow which meant we could avoid rebuilding it as part of the deploy job).

Closes #3342.

[1]: https://gds.blog.gov.uk/2022/07/12/why-weve-decided-to-decommission-gov-uk-paas-platform-as-a-service/

### CODE REVIEW

**Review by owenatgov — APPROVED** [review]
Does what it says on the tin

**Review by colinrotherham — CHANGES_REQUESTED** [review]
Would you mind sneaking in an update to the docs too please?

https://github.com/alphagov/govuk-design-system/blob/1407b33e7791e9ec2611b41871762a501ab4d544/docs/deployment/production.md#L8-L12

**Comment by colinrotherham** [comment]
@36degrees Is the logging docs page still valid, or just this bullet point?

https://github.com/alphagov/govuk-design-system/blob/1407b33e7791e9ec2611b41871762a501ab4d544/docs/logs.md#L13-L14

**Comment by 36degrees** [comment]
Good catch, but there's a separate card for updating our deployment docs on the board – happy for those to be covered as part of that?

**Comment by colinrotherham** [comment]
> Good catch, but there's a separate card for updating our deployment docs on the board (#3341) – happy for those to be covered as part of that?

Phew, sounds good

**Pull request merged**
