### PR TITLE
Update error message for bank details pattern

### PR DESCRIPTION
**Pull request by timpaul**
Based on feedback from user and guidance here: slashes are valid: https://identityandfraud.uk.experian.com/documentation/bank-wizard-api-guide-j12f/subsystems/default/country_details/roll_number_validation.htm

### CODE REVIEW

**Comment by timpaul** [comment]
@adamsilver - do you happen to know if this is correct? That '/' is a valid character in bank numbers?

**Comment by adamsilver** [comment]
@timpaul I don’t :(.

**Comment by timpaul** [comment]
No worries - that guidance is from Experian, who I would imagine know about these things!

**Comment by peteryates** [comment]
They're not included in UK bank account numbers but you do find them in some countries including the Czech Republic and Slovakia. [This reference](https://www.ecbs.org/iban.htm) might be of use.

**Comment by StephenHill-NHSBSA** [comment]
> They're not included in UK bank account numbers but you do find them in some countries including the Czech Republic and Slovakia. [This reference](https://www.ecbs.org/iban.htm) might be of use.

The original issue raised was in reference to a Building Society Roll Number rather than the Account Number.

**Comment by timpaul** [comment]
Content has been reviewed and approved

**Review by trang-erskine — APPROVED** [review]
Nikki reviewed and said it's fine.

**Pull request merged**
