### PR TITLE
Allow Node.js LTS ‘Gallium’ (v16) release version

### PR DESCRIPTION
**Pull request by colinrotherham**
Aligns our supported Node.js versions with **govuk-frontend**

1. Allows any Node.js 16 LTS release from initial launch
2. Removes `check-nvmrc` checks so we don't hold back minor/patch updates

See related PR https://github.com/alphagov/govuk-frontend/pull/2939 on resolving `npm link` issues

**`lts/gallium`** → https://github.com/alphagov/govuk-frontend/blob/main/.nvmrc
**`16.14.2`** → https://github.com/alphagov/govuk-design-system/blob/main/.nvmrc
**`16.16.0`** → https://github.com/alphagov/govuk-prototype-kit/blob/v13/.nvmrc

### CODE REVIEW

**Comment by colinrotherham** [comment]
We discussed whether `check-nvmrc` was needed in https://github.com/alphagov/govuk-frontend/pull/2842#discussion_r971040348 as `"lockfileVersion": 2` **package-lock.json** complications are now over

We're not able to add **.npmrc** `engine-strict=true` though until https://github.com/alphagov/govuk-design-system/pull/2333 is merged, otherwise npm will (correctly) flag unsupported packages such as:

```console
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: metalsmith-tagcleaner@0.0.2
npm ERR! notsup Not compatible with your version of node/npm: metalsmith-tagcleaner@0.0.2
npm ERR! notsup Required: {"node":">=4.00"}
npm ERR! notsup Actual:   {"npm":"8.19.2","node":"v16.18.0"}
```

**Comment by colinrotherham** [comment]
Node.js LTS ‘Hydrogen’ v18 is planned for launch today, but another PR can widen support when you're ready

**Review by 36degrees — APPROVED** [review]
Looks good to me – thanks for cross-referencing in the commit messages 👍🏻

**Comment by colinrotherham** [comment]
Update now https://github.com/alphagov/govuk-prototype-kit/pull/1712 and https://github.com/alphagov/govuk-design-system/pull/2399 are merged:

**`lts/gallium`** → https://github.com/alphagov/govuk-frontend/blob/main/.nvmrc
**`lts/gallium`** → https://github.com/alphagov/govuk-design-system/blob/main/.nvmrc
**`lts/*`** → https://github.com/alphagov/govuk-prototype-kit/blob/v13/.nvmrc

**Note:** GOV.UK Prototype Kit went with the `lts/*` alias as [**Node.js 18 LTS** was released yesterday](https://github.com/nodejs/node/releases/tag/v18.12.0).

Once development environments are upgraded, **package.json** `engines` field changed, GitHub workflows bumped up, tests pass (and Heroku stacks upgraded to match) etc we may also want the `lts/*` alias everywhere

**Pull request merged**
