### PR TITLE
Fix duplicate line in Start page pattern

### PR DESCRIPTION
**Pull request by calvin-lau-sig7**
Fixes a duplicate line in the Start page pattern, also strengthens the language a bit re: approval process.

### CODE REVIEW

**Review by owenatgov — APPROVED** [review]

**Review by 36degrees — APPROVED** [review]
Good catch!

**Comment by calvin-lau-sig7** [comment]
Holding off on merging for tiny bit – double-checking with content folks to see if removing the "usually" is as uncontroversial as I think it is.

We'd originally put "usually" in to cover the possibility of services that do not have a mainstream path in, but the sentence has since changed to remove that possbility.

**Comment by 36degrees** [comment]
Makes sense. If it's difficult to get an answer I'd suggest removing that change and just fixing the duplication?

Can always follow up with another PR.

**Comment by calvin-lau-sig7** [comment]
Going to merge on the logic that if an exception does not need agreement, that'd need to be agreed. Context is that content folks have asked the the language to be clearer / stronger on the point.

**Pull request merged**
