### PR TITLE
Update screenshot images to new style step by step

### PR DESCRIPTION
**Pull request by CharlotteDowns**
## What
Update the screenshots that appear on the [step by step navigation pattern](https://design-system.service.gov.uk/patterns/step-by-step-navigation/) page

## Why
It was identified that the screenshots were out of date with the live version seen in [this issue](https://github.com/alphagov/govuk-design-system/issues/1940)

### CODE REVIEW

**Comment by CharlotteDowns** [comment]
@domoscargin @lfdebrux I've made them all 1000px in resolution, what do you think?

**Comment by joelanman** [comment]
commented on slack but copying here:

trying https://squoosh.app, I can get the images smaller using the gif option.

I like your idea of keeping the screenshots high res for zooming, maybe this can help with the file size?

**Comment by CharlotteDowns** [comment]
I've just added all images at 1444px wide ready to compress with a third party tool

**Comment by domoscargin** [comment]
I've compressed the images and kept them PNGs. File size decrease all round, despite largely being higher resolution.

**Comment by domoscargin** [comment]
Going to see if there are any further file size reductions when using gifs - Squoosh supports this on Safari, but not on Chrome, so I missed it.

**Review by joelanman — APPROVED** [review]
very crisp, looks great!
small thing - the 'and' example is bigger than the 'or' example but we can always fix that in another PR if we want to

**Review by christopherthomasdesign — APPROVED** [review]

**Pull request merged**
