### PR TITLE
Add text to secondary exit this page link

### PR DESCRIPTION
**Pull request by 36degrees**

### CODE REVIEW

**Review by owenatgov — APPROVED** [review]
Thanks!

Could we also add text within the example explaining how to interact with it, similar to what we do with the [skiplink component](https://design-system.service.gov.uk/components/skip-link/)? Happy to raise a separate PR.

**Comment by davidc-gds** [comment]
For the Exit this Page skip link button code example on the Exit this Page component page, should we also add the instruction text we use for the 'Skip link' code example? That way people know how to press 'tab' to make the secondary Exit this Page button visible.

> To view the Exit this Page 'secondary link' tab to this example, or click inside this example and press tab.

**Comment by 36degrees** [comment]
Pushed a second commit – let me know if you're happy with that.

**Comment by davidc-gds** [comment]
> Pushed a second commit – let me know if you're happy with that.

Ahh yep, speedy! I was too quick to comment, evidently 😂

**Comment by owenatgov** [comment]
@36degrees Incredible. Thanks!

**Pull request merged**
