### PR TITLE
Typo fix: Mark task as "completed" not "complete"

### PR DESCRIPTION
**Pull request by frankieroberto**

### CODE REVIEW

**Comment by frankieroberto** [comment]
@calvin-lau-sig7 @lfdebrux minor fix.

I’d also be tempted to move the full stop outside of the quotation mark – I know that goes against the normal style guide, but it might be better here to be super clear that the full stop is not part of the status that you should mark the section as?

**Comment by calvin-lau-sig7** [comment]
Thanks Frankie — and agree on the 2nd point, looks like we do do that on similar sentences like Error messages. I can do a new commit in a bit.

**Comment by frankieroberto** [comment]
@calvin-lau-sig7 ok, great. Let's merge this, and I'll leave you to pick up the full stop / quote mark order separately?

**Review by calvin-lau-sig7 — APPROVED** [review]

**Comment by 36degrees** [comment]
@frankieroberto the two commits seem to cancel each other out – guessing that may not be intentional? Currently the 'files changed' tab shows zero changes.

**Comment by frankieroberto** [comment]
> @frankieroberto the two commits seem to cancel each other out – guessing that may not be intentional? Currently the 'files changed' tab shows zero changes.

@36degrees Opps, not sure what happened there... 😕  I tried to fix but then realised that #2037 fixes this anyway, so closing this PR. 👍

**Pull request closed without merging**
