### PR TITLE
Update Node to Active LTS version v16 (Gallium)

### LINKED ISSUE #2021: Update Node.js to active LTS version
## What

Update the project to use the latest active Long Term Support (LTS) version of Node.js for development, testing, and deployment.

## Why

This project currently uses Node.js version 14, which has been in maintenance since last October (2021-10-19) and won't receive new features.

## Who needs to work on this

Developer

## Who needs to review this

Developer, Tech lead

## Done when

- [ ] Update `.nvmrc`
- [ ] Update `package-lock.json` to use lockfile v2

### PR DESCRIPTION
**Pull request by domoscargin**
Node.js v14 has been in maintenance mode from 19 October 2021. v16 is the active LTS version.

This in turns updates NPM to v8, meaning our lockfile has change to [`lockfileVersion` 2](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json#lockfileversion)

This is an internal change that affects development, testing and deployment.

Closes #2021

### CODE REVIEW

**Comment by querkmachine** [comment]
Unfortunately updating to Node 16.x seems to prevent building on Apple Silicon Macs, with node-sass complaining that it doesn't have a version compatible with that version/architecture combination. That tracks, as node-sass doesn't have *any* arm64 architecture support, and would normally run under Rosetta. 

Weirdly, it doesn't complain under Node 14.x, despite node-sass also not having a Node 14/arm64 version.

```
Error: Node Sass does not yet support your current environment: OS X Unsupported architecture (arm64) with Node.js 16.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v7.0.1
    at module.exports (/Users/kimberly.grey/Sites/govuk-design-system/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/kimberly.grey/Sites/govuk-design-system/node_modules/node-sass/lib/index.js:13:35)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/kimberly.grey/Sites/govuk-design-system/node_modules/metalsmith-sass/lib/index.js:4:14
    at Object.<anonymous> (/Users/kimberly.grey/Sites/govuk-design-system/node_modules/metalsmith-sass/lib/index.js:135:2)
```

I also get this (similarly nonsensical) warning running `npm install` under Node 16.x, which isn't present when running it under Node 14.x. 

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'metalsmith-tagcleaner@0.0.2',
npm WARN EBADENGINE   required: { node: '>=4.00' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
npm WARN EBADENGINE }
```

This occur regardless of what terminal application or shell I use, so it doesn't appear to be influenced by one or more reporting incorrect environment information.

**Comment by domoscargin** [comment]
> There are no plans to support M1 with the node-sass compiler. You can switch to the sass compiler instead.

https://github.com/dlmanning/gulp-sass/issues/803#issuecomment-869580225

**Comment by domoscargin** [comment]
I got this working locally by running:

`npm uninstall node-sass -g && npm cache clean -force && npm install node-sass`

But I'm also getting the `metalsmith-tagcleaner` warning. That package is 6 years old!

**Comment by querkmachine** [comment]
Unfortunately still not working for me after trying the uninstall/clean/install commands, same error as before.

**Comment by domoscargin** [comment]
@querkmachine and I managed to get this working by following my updated comment above.

**Review by lfdebrux — APPROVED** [review]
🚢 🚀 🎉

**Pull request merged**
