### PR TITLE
Use standalone Terser minifier via Rollup task

### PR DESCRIPTION
**Pull request by colinrotherham**
This PR splits out commits from:

* https://github.com/alphagov/govuk-design-system/pull/2497

Including:

1. Update to [`rollup@0.59.4`](https://github.com/rollup/rollup/releases/tag/v0.59.4) maintaining legacy IE8 support
2. Replace [`metalsmith-rollup`](https://github.com/attila/metalsmith-rollup#readme) with standalone Rollup task
3. Replace [`metalsmith-uglify`](https://github.com/borisovg/metalsmith-uglify#readme) with standalone Terser task

For information on UglifyJS vs terser see:

* https://github.com/alphagov/govuk-frontend/pull/3013

### CODE REVIEW

**Comment by colinrotherham** [comment]
@domoscargin This one is ready to review complete with some basic Rollup tests

**Review by domoscargin — APPROVED** [review]
I've poked around on IE8 and IE11 and Safari 9 & 12 and things look OK to me.

Obviously there's a diff between minified files. I can't see why there'd be issues with older browsers given the config we've passed to Terser, but I've had a gander at various JS-heavy component pages in IE8 through 11 and it looks... well, awful, but as good as IE8 gets, with no obvious bugs.

**Comment by colinrotherham** [comment]
Thanks @domoscargin, appreciate the checks

Will rebase, fix the conflicts, and get it merged 😊

**Comment by colinrotherham** [comment]
As a nice bonus, @dependabot has closed these two:

* https://github.com/alphagov/govuk-design-system/pull/2434
* https://github.com/alphagov/govuk-design-system/pull/2450

This PR added [`rollup0.59.4`](https://github.com/alphagov/govuk-design-system/pull/2539/commits/462b4f8af73679e1ea6deffdd6113d564ab821d4) for IE8 which invalidated `peerDependency` ranges of the PRs above

**Pull request merged**
