### PR TITLE
Use the same version of `marked` in our build and our plugins

### PR DESCRIPTION
**Pull request by colinrotherham**
Re-opened from https://github.com/alphagov/govuk-design-system/pull/3130 because @dependabot closed the PR it was based on, which closed our PR too

---

Unblocks `marked@9.0.2` via https://github.com/alphagov/govuk-design-system/pull/3157 and closes:

* https://github.com/alphagov/govuk-design-system/issues/2767

HTML changes include:

1. Automatic "smart" punctuation is unescaped `&#8216;` → `‘` everywhere
2. Automatic "smart" punctuation is now applied to Nunjucks rendered HTML
3. Indentation is better preserved around code blocks
4. Macro options Markdown now shares the same renderer

### CODE REVIEW

**Comment by domoscargin** [comment]
Copy pasting from the previous PR:

Diff appears to mostly be:

- formatting changes to the code blocks,
- nice pick ups from smartypants that we've missed
  -  We should edit [this example code](https://github.com/alphagov/govuk-design-system/blob/f5a4007208f78fd5f0189bfbb48e562407724001/views/partials/_example.njk#L87-L93), since there's a LOT of instances of it that smartpants has to transform. There's a few others in the diff, but none of them appear 312 times 😆  Quite a few of them come from the `govuk-frontend` YAML properties, so we could potentially `grep` and replace there to reduce transformations further.

However, there is some weirdness, like:

## Replacing `--` with `–` in some examples
```diff
diff --color -r .cache/public/get-started/updating-your-code/index.html deploy/public/get-started/updating-your-code/index.html
1146c1153
<       <td class="govuk-table__cell ">govuk-section-break<br>govuk-section-break--visible<br>govuk-section-break--xl<br>govuk-section-break--l<br>govuk-section-break--m</td>
---
>       <td class="govuk-table__cell ">govuk-section-break<br>govuk-section-break–visible<br>govuk-section-break–xl<br>govuk-section-break–l<br>govuk-section-break–m</td>
1167c1174
<       <td class="govuk-table__cell ">govuk-list<br>govuk-list--bullet</td>
---
>       <td class="govuk-table__cell ">govuk-list<br>govuk-list–bullet</td>
1171c1178
<       <td class="govuk-table__cell ">govuk-list<br>govuk-list--number</td>
---
>       <td class="govuk-table__cell ">govuk-list<br>govuk-list–number</td>
1242c1249
<       <td class="govuk-table__cell ">govuk-label--s</td>
---
>       <td class="govuk-table__cell ">govuk-label–s</td>
```
Suspect we just want to wrap these in `<code>`

## Some component options tables are weird?
For some reason, the Notification Banner and Summary List component Nunjucks options tables are showing up as big diffs (though they look like they're just getting a bit of formatting). The Summary List options tables are about 5000+ lines of the diff file.

Is there something funky with the page code that's affecting these tables versus other components where the tables are not getting reformatted?

**Comment by colinrotherham** [comment]
Ahh well spotted @domoscargin, default support for `--` → `–` is too risky for CSS classes

I've pushed a commit https://github.com/alphagov/govuk-design-system/pull/3134/commits/5208150d6291c37df5dc72d30325780feacdd12a to [configure](https://github.com/othree/smartypants.js#options-and-configuration) quotes and ellipses only

Diffs wise, I've got expected changes only for Notification banner and Summary list. Do you mind checking if it's not one of the other PRs that merged recently? This PR is based on https://github.com/alphagov/govuk-design-system/pull/3133 now

**Review by domoscargin — APPROVED** [review]
I'm a little concerned about some tables getting reformatted, but others not, but I'm assuming it's just to do with the content within those tables and not anything nefarious, since as you mentioned, it's just formatting changes.

So, happy to approve!

**Comment by colinrotherham** [comment]
Thanks @domoscargin

**Pull request merged**
