### PR TITLE
Update what's new and roadmap for 4.2.0

### PR DESCRIPTION
**Pull request by domoscargin**
## What

I've removed some earlier stuff in the "recently shipped" section, because we're quite a few releases away from that now.

Not sure if we need to make any other roadmap changes?

### CODE REVIEW

**Comment by querkmachine** [comment]
Localisation support can probably be safely added to the 'currently working on' section!

**Comment by calvin-lau-sig7** [comment]
Looks great, thanks everyone!

**Comment by 36degrees** [comment]
Rebased to bring in the changes from main and get the tests passing.

**Comment by 36degrees** [comment]
Rebased again to resolve a conflict in the roadmap (since the deleted line about pagination was already removed in #1972)

**Pull request merged**
