### PR TITLE
Update privacy policy and cookies content

### PR DESCRIPTION
**Pull request by m-green**
This PR updates content in line with https://github.com/alphagov/govuk-design-system/pull/1106:

- updates privacy policy page
- removes cookies page as there are no longer any cookies stored

Do not merge until:

- PR also removes cookie banner (@nickcolley will add)
- developer has checked for factual accuracy
- another content designer has 2i'd

### CODE REVIEW

**Comment by 36degrees** [comment]
The link to the cookies page in the footer also needs to be removed.

(The build is failing because it's detecting broken links from the cookie banner and the footer)

**Comment by m-green** [comment]
> The link to the cookies page in the footer also needs to be removed.
> 
> (The build is failing because it's detecting broken links from the cookie banner and the footer)

Good point! Will fix.

**Comment by nickcolley** [comment]
@m-green I'm fixing that

**Comment by m-green** [comment]
Content updates have now been 2i'd by Tracy - no changes.

**Pull request merged**
