### PR TITLE
Update index.md.njk

### PR DESCRIPTION
**Pull request by StephenGill**
Added explanation of layout options and line length, as per https://github.com/alphagov/govuk-design-system/issues/1126

Need review from @christopherthomasdesign

### CODE REVIEW

**Comment by joelanman** [comment]
This sounds like 2/3 is the only layout people should use? I think there are cases where another layout might be needed.

**Comment by StephenGill** [comment]
What would you say? Something like -

> For most pages, we recommend using either a 'two-thirds' or a 'two-thirds / one third layout'.

?

**Comment by joelanman** [comment]
Sounds good yeh

**Comment by StephenGill** [comment]
okies, have updated the PR

**Comment by StephenGill** [comment]
@joelanman would you mind merging this, if you're happy with it (Chris has given it the thumbs up, but he doesn't have write access).

**Comment by nickcolley** [comment]
@StephenGill when you propose a change to the team, if you have been given approval by the relevant people, you then merge your own work.

**Comment by StephenGill** [comment]
Sorry, still getting used to the protocols. Do I mean 'please review'?

**Comment by nickcolley** [comment]
@StephenGill when you raise the pull request you can ask someone on the team for a review, once they have reviewed and given you an 'approval', then you can merge this.

So maybe"@joelanman can you give me an approval please?", once Joe has done that you can press the merge button.

**Comment by nickcolley** [comment]
I've approved it on behalf of Joe since he said it looks good.

**Comment by StephenGill** [comment]
Thanks

**Pull request merged**
