### PR TITLE
Show nested option type in table captions

### PR DESCRIPTION
**Pull request by colinrotherham**
Just splitting out some ideas from https://github.com/alphagov/govuk-design-system/pull/2892

This PR adds the nested option `type` to macro option table captions

## Before

* **Options for `example`** – Used for nested arrays, objects and components

## After

* **Options for `example` object** – Used for nested objects
* **Options for `example` array** – Used for nested arrays (without params)
* **Options for `example` array objects** – Used for nested arrays (with params)
* **Options for `example` component** – Used for nested components

| Before  | After |
| ------- | ----- |
| Table captions for nested options | Table captions for nested options showing types |

### CODE REVIEW

**Comment by christopherthomasdesign** [comment]
I personally really like the way this draws a visual link between the options and the code above.

I don’t think we use code examples in headings elsewhere like this, so want to get more designers’ eyes on it to check they think it looks ok – what do you think @CharlotteDowns / @Ciandelle ?

**Review by 36degrees — APPROVED** [review]
Code change looks good, but can we get a second pair of eyes from design as requested:

> I don’t think we use code examples in headings elsewhere like this, so want to get more designers’ eyes on it to check they think it looks ok – what do you think @CharlotteDowns / @Ciandelle ?

Can we also remove `[SPIKE]` from the PR title if we're going to merge this as-is.

**Comment by stevenjmesser** [comment]
Styling code examples in headings make sense to me visually, but are there any accessibility impacts, @colinrotherham?

**Comment by colinrotherham** [comment]
@stevenjmesser Just waiting to hear back: https://gds.slack.com/archives/C0447D0STV0/p1695139312117359

**Comment by colinrotherham** [comment]
@stevenjmesser Also https://gds.slack.com/archives/C011V7RAAKY/p1695138391634739

**Comment by CharlotteDowns** [comment]
I like the use of the code in these instances. I think it makes the action much clearer visually.

**Pull request merged**
