### PR TITLE
Update design-system-team.md

### PR DESCRIPTION
**Pull request by kellylee-gds**
Add Kam to the team page.

### CODE REVIEW

**Review by owenatgov — APPROVED** [review]
EZ

**Comment by kellylee-gds** [comment]
@owenatgov some of the tests are failing 😭 when you have a mo could you take a look?

**Comment by owenatgov** [comment]
Ah don't worry this is a known flakey test. Re-running it should sort it out. 2 tics.

**Comment by kellylee-gds** [comment]
@owenatgov thank you!

**Pull request merged**
