### PR TITLE
Write out support email address

### PR DESCRIPTION
**Pull request by igloosi**
Write out the support email (for easier copy & paste where non-native mail client is used) on: 
- Homepage support section:  #397
- Contact panel panel on every styles, component and pattern page

### CODE REVIEW

**Comment by 36degrees** [comment]
There's also the 'Get in touch' block at the bottom of every styles, component and pattern page – https://github.com/alphagov/govuk-design-system/blob/master/views/partials/_contact-panel.njk

**Comment by igloosi** [comment]
cool, updated

**Comment by nickcolley** [comment]
Spam bots would parse the mailto: link?

**Comment by alex-ju** [comment]
@nickcolley: indeed. it's not related to this change, was just a thought around it

**Pull request merged**
