### PR TITLE
Update postcode guidance

### PR DESCRIPTION
**Pull request by terrysimpson99**

### CODE REVIEW

**Comment by aliuk2012** [comment]
This PR relates to [this discussion](https://github.com/alphagov/govuk-design-system-backlog/issues/31#issuecomment-491877932)

**Comment by amyhupe** [comment]
Hi @terrysimpson99 - thanks for your patience on this.

I've reviewed the content and I think it's mostly good but I want to suggest a couple of changes to the placement and structure. 

I've done that as a separate PR (#918) as I didn't want to overwrite your version. Could you take a look? If you're happy, we can close this PR and merge the other one?

**Comment by terrysimpson99** [comment]
Hi @amyhupe I'm generally happy with the changes you've made. However, I wanted it to be clear that unnecessary characters should be ignored at the beginning, middle, and end. For example Royal Mail (`https://www.royalmail.com/find-a-postcode`) ignore undesirable characters in the middle and end but not at the beginning. If you understand what I mean and can encapsulate that, I'm fine with closing this PR and merging the other one.

**Comment by amyhupe** [comment]
Hi @terrysimpson99 – I've now added "beginning, middle and end" as you asked. I'm going to close this PR now and get someone to approve the other one.

**Pull request closed without merging**
