### PR TITLE
Update link to NCSC password research

### PR DESCRIPTION
**Pull request by jonodrew**
The old link redirected to the new NCSC home page, so I've updated the link to point to the new home for password research. Many thanks to @joelgsamuel for the tip off.

### CODE REVIEW

**Comment by 36degrees** [comment]
The National Archives has a copy of the old URL:

https://webarchive.nationalarchives.gov.uk/20180924155514/https://www.ncsc.gov.uk/index/guidance?f%5B0%5D=field_topics%253Aname%3AIdentity%20and%20passwords

Not sure if the proposed URL is the right place to take people. We could consider linking to the 'passwords' topic page, which seems closer, but still doesn't seem to link to the same content?

https://www.ncsc.gov.uk/section/advice-guidance/all-topics?topics=Passwords

**Comment by jonodrew** [comment]
Hey @36degrees , what do you think? I'm confident that the link I put in goes to the right content and the thread seems to have dried up.

**Comment by jonodrew** [comment]
Can anyone else take a look at this please?

**Comment by aliuk2012** [comment]
Hi @jonodrew 

We reviewed this PR this afternoon and agreed as a team that this should definitely be updated but to the shortened url of `https://www.ncsc.gov.uk/collection/passwords`. 

Would you be able to update your changes to use `https://www.ncsc.gov.uk/collection/passwords` or would you prefer us to update it on your behalf?

Thank you once again for bringing this to our attention and for submitting this PR.

**Pull request merged**
